[package]
name = "mcwr"
version = "0.1.4"
edition = "2021"
authors = ["k3nder"]
license = "GPL-3.0-only"
description = "A MC WRAPPER CREATOR"

[dependencies]
mclr = "2.3.5"
clap = { version = "4.5.28", features = ["derive"] }